CREATE TABLE PELANGGAN (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAMA VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ALAMAT VARCHAR(50) NOT NULL,
    NO_HP VARCHAR(25)
);