CREATE TABLE PEMBAYARAN (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PELANGGAN_ID INT(50) NOT NULL,
    METODE_PEMBAYARAN VARCHAR(50) NOT NULL,
    TOTAL_PEMBAYARAN DECIMAL(50) NOT NULL,
    TANGGAL DATE NOT NULL
);