CREATE TABLE PENGIRIMAN (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PESANAN_ID INT(50) NOT NULL,
    METODE_PENGIRIMAN VARCHAR(50) NOT NULL,
    ALAMAT VARCHAR(100) NOT NULL
);

SHOW TABLES;

desc pengiriman;