CREATE TABLE PESANAN(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PELANGGAN_ID INT,
    TANGGAL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES PELANGGAN(ID)
);