-- Melihat Kategori barang yang paling banyak barangnya.

SELECT
    CATEGORIES.CATEGORY_ID,
    CATEGORIES.CATEGORY_NAME,
    COUNT(PRODUCTS.PRODUCT_ID) AS TOTAL_PRODUCTS
FROM
    CATEGORIES
    JOIN PRODUCTS
    ON CATEGORIES.CATEGORY_ID = PRODUCTS.CATEGORY_ID
GROUP BY
    CATEGORIES.CATEGORY_ID
ORDER BY
    TOTAL_PRODUCTS DESC LIMIT 1;