SELECT
    PESANAN.ID,
    PELANGGAN.NAME,
    COUNT(DISTINCT DETAIL_PESANAN.ID) AS TOTAL_DIFFERENT_PRODUK
FROM
    PESANAN
    JOIN PELANGGAN
    ON PESANAN.ID = PESANAN.ID JOIN DETAIL_PESANAN
    ON PESANAN.ID = DETAIL_PESANAN.ID
GROUP BY
    PESANAN.ID
HAVING
    TOTAL_DIFFERENT_PRODUK = 3;